- name: Install Home Assistant Stream Deck Addon
  hosts: streamdeck-host
  tasks:
    - name: Install the requirements
      ansible.builtin.apt:
        update_cache: true
        name:
          - libudev-dev
          - libusb-1.0-0-dev
          - libhidapi-libusb0
          - libffi-dev
          - libcairo2
          - git
          - python3
          - python3-pip
      become: true

    - name: Clone the repo
      ansible.builtin.git:
        repo: https://github.com/basnijholt/home-assistant-streamdeck-yaml
        dest: "{{ ansible_user_dir }}/home-assistant-streamdeck-yaml"

    - name: Install the python requirements
      ansible.builtin.pip: 
        name: git+https://github.com/basnijholt/home-assistant-streamdeck-yaml
        break_system_packages: true
        editable: true
      
    - name: Copy Streamdeck configuration
      ansible.builtin.template:
        src: "./files/configuration.yaml.j2"
        dest: "{{ ansible_user_dir }}/home-assistant-streamdeck-yaml/configuration.yaml"
    
    - name: Copy udev rule
      ansible.builtin.template:
        src: "./files/99-streamdeck.rules.j2"
        dest: "/etc/udev/rules.d/99-streamdeck.rules"
      become: true

    - name: Reload udev rules
      ansible.builtin.command: "udevadm control --reload-rules"
      become: true

    - name: Copy .env file
      ansible.builtin.template:
        src: "./files/.env.example.j2"
        dest: "{{ ansible_user_dir }}/home-assistant-streamdeck-yaml/.env"

    - name: Install the service
      ansible.builtin.template:
        src: "./files/streamdeck.service.j2"
        dest: "/etc/systemd/system/streamdeck.service"
      become: true

    - name: Start the service
      ansible.builtin.service:
        name: streamdeck
        state: started
        enabled: true
    